version: "20.10.2"
networks:
  tplus-ss-481:

services:
  eureka:
    build: ./yethi-service-discovery
    image: yethi-service-discovery
    container_name: eureka
    ports:
      - 8761:8761
    networks:
      - tplus-ss-481
  